### ISSUE TITLE
As a hall admin, I can create hall events

### ISSUE THREAD

**Issue by jieffyy** [AY2021S1-CS2103T-T11-2/tp#91]
- [x] Create Events module (refer to Person module) - Done by #104.
- [x] Create command for hall-events - Done by #108.
- [x] Persist to device - Done by #115
